apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart
spec:
  replicas: 2
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      name: saklogin
      labels:
        name: deployment
    spec:
      containers:
        - name: login
          image: manojshetty2021/netflix:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: flipkart-svc
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30070
  selector:
    name: deployment
  type: NodePort
