apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      name: dev
      labels:
        name: deployment
    spec:
      containers:
        - name: signup
          image: sakit333/zomatoapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: netflix-svc
spec:
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30070
  selector:
    name: deployment
  type: NodePort
